from __future__ import annotations
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo
from jinja2 import Template
TPL=r'''<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="300"><title>مساعد التداول الشخصي</title><style>
:root{--b:#07101e;--p:#101a2c;--q:#0b1424;--t:#edf3ff;--m:#98a7c4;--l:#263754;--g:#22c55e;--a:#f59e0b;--r:#ef4444;--c:#38bdf8}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--t);font-family:system-ui,Tahoma,Arial}.w{max-width:1250px;margin:auto;padding:16px}.h{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.m{color:var(--m)}.kpis,.grid{display:grid;gap:12px}.kpis{grid-template-columns:repeat(auto-fit,minmax(155px,1fr));margin:14px 0}.grid{grid-template-columns:repeat(auto-fit,minmax(330px,1fr))}.k,.c{background:var(--p);border:1px solid var(--l);border-radius:16px;padding:14px}.k b{font-size:1.25rem;display:block}.top{display:flex;justify-content:space-between;gap:10px}.decision{padding:10px;border-radius:10px;background:var(--q);margin:10px 0;border:1px solid var(--c)}.BUY_NOW{border-color:var(--g)}.NO_TRADE{border-color:var(--r)}.lv{display:grid;grid-template-columns:1fr 1fr;gap:7px}.lv div{background:var(--q);padding:8px;border-radius:9px}.small{font-size:.87rem;line-height:1.6}.Aplus,.A{color:var(--g)}.B{color:var(--a)}.C{color:var(--m)}</style></head><body><div class="w">
<div class="h"><div><h1>مساعد التداول الشخصي</h1><div class="m">قرارات مبسطة • دقة قابلة للقياس • التنفيذ يدوي</div></div><div class="m">{{ updated }}</div></div>
<div class="kpis"><div class="k">المحرك<b>{{ performance.engine or 'V4' }}</b></div><div class="k">حالة السوق<b>{{ regime.label }}</b></div><div class="k">أفضل فرصة<b>{{ best.symbol if best else '-' }} {{ best.quality_grade if best else '' }}</b></div><div class="k">الدقة المقاسة<b>{{ performance.signal_accuracy.win_rate if performance.signal_accuracy else 0 }}%</b></div><div class="k">نتائج مكتملة<b>{{ performance.signal_accuracy.samples if performance.signal_accuracy else 0 }}</b></div><div class="k">P/L اليوم<b>{{ performance.daily_pnl_pct or 0 }}%</b></div></div>
<h2>القرارات الحالية</h2><div class="grid">{% for s in signals %}<div class="c"><div class="top"><b>{{ s.symbol }} · {{ 'يومي' if s.strategy=='DAY' else 'سوينغ' }}</b><b class="{{ 'Aplus' if s.quality_grade=='A+' else s.quality_grade }}">{{ s.quality_grade }} · {{ s.score }}/100</b></div><h2>${{ '%.2f'|format(s.price) }}</h2><div class="decision {{ s.action }}"><b>{{ s.simple_decision_ar }}</b><br>{{ s.simple_next_step }}</div><div class="lv"><div>الدخول<b><br>${{ '%.2f'|format(s.entry_low) }}–${{ '%.2f'|format(s.entry_high) }}</b></div><div>وقف الخسارة<b><br>${{ '%.2f'|format(s.stop_loss) }}</b></div><div>الهدف الأول<b><br>${{ '%.2f'|format(s.target1) }}</b></div><div>الهدف الثاني<b><br>${{ '%.2f'|format(s.target2) }}</b></div><div>الكمية<b><br>{{ s.suggested_shares }}</b></div><div>المخاطرة<b><br>{{ s.risk_label }}</b></div><div>السوق<b><br>{{ s.market_regime_v2 }}</b></div><div>المجموعة<b><br>{{ s.precision.group }}</b></div></div><p class="small m">{% if s.precision.blockers %}سبب الانتظار/الحذر: {{ s.precision.blockers[0] }}{% else %}لا توجد عوائق رئيسية مسجلة حاليًا.{% endif %}</p></div>{% endfor %}</div><p class="m small">الهدف من النظام هو تقليل القرارات الضعيفة، وليس إنتاج صفقة كل مرة. عدم الدخول نتيجة صحيحة عندما لا تكتمل الشروط.</p></div></body></html>'''
def render(signals,output,timezone,regime,portfolio,performance):
    signals=sorted(signals,key=lambda x:(x.get('action')=='BUY_NOW',x.get('quality_grade') in ('A+','A'),x.get('score',0)),reverse=True);best=next((x for x in signals if x.get('action') in ('BUY_NOW','WAIT_FOR_ENTRY')),signals[0] if signals else None);updated=datetime.now(ZoneInfo(timezone)).strftime('%Y-%m-%d %H:%M %Z');html=Template(TPL).render(signals=signals,updated=updated,regime=regime,portfolio=portfolio,performance=performance,best=best);p=Path(output);p.parent.mkdir(parents=True,exist_ok=True);p.write_text(html,encoding='utf-8')
